# Generated by Django 3.2.7 on 2021-11-13 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('matchID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('matchDate', models.DateField()),
                ('matchTime', models.TimeField()),
                ('venue', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('classes', models.CharField(max_length=100)),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('trmtName', models.CharField(max_length=100)),
                ('sportsType', models.CharField(choices=[('cricket', 'Cricket'), ('football', 'Football'), ('volleyball', 'Volleyball')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MatchView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batsman', models.CharField(max_length=100)),
                ('bowler', models.CharField(max_length=100)),
                ('run', models.CharField(max_length=100)),
                ('wicket', models.CharField(max_length=100)),
                ('match_ref_id', models.CharField(max_length=100)),
                ('bowlerType', models.CharField(default='temporary', max_length=100)),
                ('extraRunType', models.CharField(default='temporary', max_length=100)),
                ('extraRun', models.CharField(default='temporary', max_length=100)),
                ('ballNo', models.CharField(default='temporary', max_length=100)),
                ('outBatsman', models.CharField(default='temporary', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('schoolID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('schoolName', models.CharField(max_length=100)),
                ('schoolAddress', models.CharField(max_length=100)),
                ('schoolThana', models.CharField(max_length=100)),
                ('postCode', models.CharField(max_length=100)),
                ('subDistrict', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('phoneNo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('contPerName', models.CharField(max_length=100)),
                ('schlUname', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('schoolType', models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Madrassa', 'Madrassa')], max_length=100)),
                ('studentType', models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls'), ('Coed', 'Coed')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VolleyBallModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerID', models.CharField(max_length=100)),
                ('timestamp', models.CharField(max_length=100)),
                ('match_ref_id', models.CharField(default='temporary', max_length=100)),
                ('setNo', models.CharField(default='temporary', max_length=100)),
                ('team1Point', models.CharField(default='temporary', max_length=100)),
                ('team2Point', models.CharField(default='temporary', max_length=100)),
                ('action', models.CharField(default='temporary', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('teamName', models.CharField(max_length=100)),
                ('sportsType', models.CharField(choices=[('cricket', 'Cricket'), ('football', 'Football'), ('volleyball', 'Volleyball')], max_length=100)),
                ('numOfPlayer', models.CharField(max_length=100)),
                ('player1', models.CharField(max_length=100)),
                ('player2', models.CharField(max_length=100)),
                ('player3', models.CharField(max_length=100)),
                ('player4', models.CharField(max_length=100)),
                ('player5', models.CharField(max_length=100)),
                ('player6', models.CharField(max_length=100)),
                ('player7', models.CharField(max_length=100)),
                ('player8', models.CharField(max_length=100)),
                ('player9', models.CharField(max_length=100)),
                ('player10', models.CharField(max_length=100)),
                ('player11', models.CharField(max_length=100)),
                ('schoolID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.school')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('playerID', models.CharField(default='p', max_length=100, primary_key=True, serialize=False)),
                ('fName', models.CharField(max_length=100)),
                ('lName', models.CharField(max_length=100)),
                ('birthDate', models.DateTimeField()),
                ('ageGroup', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('playerAddress', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('postCode', models.CharField(max_length=100)),
                ('parentName', models.CharField(max_length=100)),
                ('parentPhoneNo', models.CharField(max_length=100)),
                ('parentWorkPlace', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=100)),
                ('schoolID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.school')),
            ],
        ),
        migrations.CreateModel(
            name='MatchExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toss', models.CharField(max_length=100)),
                ('over', models.IntegerField()),
                ('result', models.CharField(max_length=100)),
                ('matchID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.match')),
            ],
        ),
    ]
