# Generated by Django 3.2.7 on 2021-11-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchextra',
            name='batting',
            field=models.CharField(default='temporary', max_length=100),
        ),
        migrations.AddField(
            model_name='matchextra',
            name='bowling',
            field=models.CharField(default='temporary', max_length=100),
        ),
    ]
