# Generated by Django 3.2.7 on 2021-12-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_footballmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footballmodel',
            old_name='action',
            new_name='attack',
        ),
        migrations.AddField(
            model_name='footballmodel',
            name='defence',
            field=models.CharField(default='temporary', max_length=100),
        ),
        migrations.AddField(
            model_name='footballmodel',
            name='passing',
            field=models.CharField(default='temporary', max_length=100),
        ),
        migrations.AddField(
            model_name='footballmodel',
            name='running',
            field=models.CharField(default='temporary', max_length=100),
        ),
    ]
