# Generated by Django 3.2.7 on 2021-12-03 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20211203_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballmodel',
            name='team1Score',
        ),
        migrations.RemoveField(
            model_name='footballmodel',
            name='team2Score',
        ),
    ]
